type Aluno{
    Id: ID!
    ra: int!
    nome: String!
    email: String!
}

type Query{
    alunos: [Aluno]
    aluno(id: ID!): Aluno
}

type Mutation{
    createAluno(ra: int!, nome: String!, email: String!): Aluno!
    updateAluno(id: ID!, ra: int!, nome: String!, email: String!): Aluno!
    deleteAluno(id: ID!): Aluno!
}